pages:
  stage: deploy
  artifacts:
    paths:
      - public
    exclude:
      - public/test/**/* # Exclude test files from the artifacts.
      - public/**/*.map
      - public/**/*.LICENSE.txt
  only:
    - main
