image: node:lts-slim

stages:
  - build
  - deploy

# This folder is cached between builds
# https://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - .cache/

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir .pnpm-store

pnpm:install:
  stage: build
  script:
    - pnpm install -r --frozen-lockfile --prod # add dependencies to .pnpm-store
  only:
    - main

pages:
  stage: deploy
  needs:
    - pnpm:install
  script:
    - npx playwright install --with-deps chromium # Install Chromium for Playwright
    - pnpm install -r --frozen-lockfile --prod --offline # link dependencies from .pnpm-store
    - ./node_modules/.bin/gatsby info
    - ./node_modules/.bin/gatsby build --prefix-paths
    - du -sh public/ # Check the size of the unzipped artifacts.
  artifacts:
    paths:
      - public
    exclude:
      - public/**/*.map
      - public/**/*.LICENSE.txt
  only:
    - main
