pages:
  stage: deploy
  script:
    - touch worst-server-i-have-seen.txt
  artifacts:
    paths:
      - public
    exclude:
      - public/test/**/* # Exclude test files from the artifacts.
      - public/**/*.map
      - public/**/*.LICENSE.txt
  only:
    - main
