image: node:lts-slim

stages:
  - build
  - deploy

# This folder is cached between builds
# https://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/
  key:
    files:
      - package-lock.json

before_script:
  - npm ci --cache .npm --prefer-offline

npm:install:
  stage: build
  script:
    - npm install
  only:
    - main

pages:
  stage: deploy
  script:
    - ./node_modules/.bin/gatsby info
    - ./node_modules/.bin/gatsby build --prefix-paths
    - du -sh public/ # Check the size of the unzipped artifacts.
  artifacts:
    paths:
      - public
    exclude:
      - public/test/**/* # Exclude test pages from the artifacts.
      - public/**/*.js.map # Exclude source maps from the artifacts.
      - public/**/*.LICENSE.txt
  only:
    - main
