image: node:lts

pages:
  stage: deploy
  artifacts:
    paths:
      - public
    script:
      - touch worst-server-i-have-seen.txt
    exclude:
      - public/test/**/* # Exclude test files from the artifacts.
      - public/**/*.map
      - public/**/*.LICENSE.txt
  only:
    - main
