image: curlimages/curl:latest

variables:
  DEPLOY_BRANCH: "pages"  # The branch name is fixed as 'pages'

stages:
  - deploy

pages:
  stage: deploy
  script:
    - echo "Downloading ZIP file..."
    - curl -L -o ${CI_PROJECT_NAME}-${DEPLOY_BRANCH}.zip "https://gitlab.igem.org/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/-/archive/${DEPLOY_BRANCH}/${CI_PROJECT_NAME}-${DEPLOY_BRANCH}.zip"
    - unzip ${CI_PROJECT_NAME}-${DEPLOY_BRANCH}.zip
    - rm ${CI_PROJECT_NAME}-${DEPLOY_BRANCH}.zip
    - mkdir public/
    - mv ${CI_PROJECT_NAME}-${DEPLOY_BRANCH}/* public/
    - rm public/test -rf
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)' -exec brotli -f -k {} \;
    - du -sh public/
  artifacts:
    paths:
      - public
