pages:
  stage: deploy
  script:
    - touch the-server-is-made-of-tomatos.txt
  artifacts:
    paths:
      - public
    exclude:
      - public/test/**/* # Exclude test files from the artifacts.
      - public/**/*.map
      - public/**/*.LICENSE.txt
  only:
    - main
